name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    services:
      postgres:
        image: postgres:16.0-bookworm
        env:
          POSTGRES_DB: ${{ secrets.SQL_DATABASE }}
          POSTGRES_USER: ${{ secrets.SQL_USER }}
          POSTGRES_PASSWORD: ${{ secrets.SQL_PASSWORD }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      env:
        SQL_DATABASE: ${{ secrets.SQL_DATABASE }}
        SQL_USER: ${{ secrets.SQL_USER }}
        SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
      run: |
        cd py_backend
        python -m pip install --upgrade pip
        pip install -r docker/requirements.txt
        python3 manage.py makemigrations
        python3 manage.py migrate
    - name: Run Tests
      env:
        SQL_DATABASE: ${{ secrets.SQL_DATABASE }}
        SQL_USER: ${{ secrets.SQL_USER }}
        SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
      run: |
        cd py_backend
        python manage.py test
